image:
  name: hashicorp/terraform:light
  entrypoint: [""]

stages:
  - deploy
  - destroy
  {% if values.infracost %}- infracost{%- endif %}

variables:
  TF_ROOT: $CI_PROJECT_DIR
  DEPLOY_JOB: 'false'
  DESTROY_JOB: 'false'
  {% if values.infracost %}INFRACOST_JOB: 'false'{%- endif %}

deploy:
  stage: deploy
  script:
    - terraform --version
    - terraform init
    - terraform apply -input=false -auto-approve
  rules:
    - if: '$DEPLOY_JOB == "true"'
  artifacts:
    name: kubeconf
    paths:
      - kube/* 
    expire_in: 1 day

destroy:
  stage: destroy
  script:
    - terraform --version
    - terraform init
    - terraform destroy -auto-approve
  rules:
    - if: '$DESTROY_JOB == "true"'

{% if values.infracost%}
infracost:
  stage: infracost
  image: ubuntu:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y software-properties-common curl unzip git
    - apt-add-repository -y ppa:git-core/ppa
    - apt-get update -qy
    - curl -LO https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
    - unzip terraform_1.3.0_linux_amd64.zip
    - chmod +x terraform
    - mv terraform /usr/local/bin/
    - terraform --version
    - terraform init
    - terraform plan -no-color -out plan_cache.json
  script:
    - curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
    - infracost --version
    - infracost breakdown --show-skipped --path plan_cache.json
  rules:
    - if: '$INFRACOST_JOB == "true"'
{%- endif %}