apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: platform-devportal-catalog-info
  description: Importing apis
spec:
  targets:
    - ./apis/*.yaml
    - ./templates/templates.yaml
    - ./environments/environments.yaml
    - ./clusters/clusters.yaml
    - ./components/components.yaml
    - ./aurora-varejo/catalog-info.yaml
    - ./aurora-varejo/templates/aurora-microservice/template.yaml
