include:
  - remote: https://gitlab.com/vkpr/templates/-/raw/1.3.7/kong-stack-template.gitlab-ci.yml

cache:
  key: $CI_PIPELINE_ID
  paths:
    - kube

variables:
  AWS_ACCESS_KEY: "$AWS_ACCESS_KEY"
  AWS_SECRET_KEY: "$AWS_SECRET_KEY"
  AWS_REGION: "$AWS_REGION"
  CLUSTER: {%- if values.cluster_name %} ${{ values.cluster_name }} {%- else %} ${{'${{'}} secrets.CLUSTER_NAME ${{'}}'}}{%- endif %}
  POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
  KONG_LICENSE: "$KONG_LICENSE"
  KONG_ADMIN_PASSWORD: "$KONG_ADMIN_PASSWORD"

stages:
  - Install_Kong

provisionament:
    stage: Install_Kong
    extends: .provisionament

kubeconfig-download:
    stage: Install_Kong
    extends: .kubeconfig-download
    needs:
    - provisionament

