apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.componentId | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
  {%- if values.host == 'github.com' %}
    github.com/project-slug: ${{values.repoUrl}}
    github.com/workflows: kong.yml
  {%- endif %}
  {%- if values.host == 'gitlab.com' %}
    gitlab.com/project-slug: ${{ values.repoUrl }}
    gitlab.com/jobs: Deploy:Install_Kong
  {%- endif %}
    backstage.io/techdocs-ref: dir:.
    vault.io/secrets-path: devportal
spec:
  type: devops
  lifecycle: experimental
  owner: ${{values.owner | dump}}
