apiVersion: backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "devportal-kubernetes"
  description: "cluster-digital-ocean"
  annotations:
    # github.com/project-slug: veecode-platform/cluster_template-do
    # backstage.io/techdocs-ref: dir:.
    veecode/cluster-name: "devportal-kubernetes" #annotations for cluster plugin
    backstage.io/kubernetes-id: devportal-kubernetes
    kubernetes.io/secret-name: devportal-kubernetes-secret
    kubernetes.io/secret-namespace: veecode-homolog
    kubernetes.io/auth-provider: serviceAccount
    kubernetes.io/api-server: https://dd69495e-d62a-426d-aa00-b4d71e43581b.k8s.ondigitalocean.com
    kubernetes.io/skip-tls-verify: "true"
    kubernetes.io/skip-metrics-lookup: "false"
    # infracost/project: devportal-kubernetes-infracost
    cluster/instructions: |
      doctl auth init --access-token $YOUR_DIGITALOCEAN_ACCESS_TOKEN
      doctl kubernetes cluster kubeconfig save
      $(doctl kubernetes cluster list -o json | jq -r '.[] 
      | select(.name=="YOUR_CLUSTER_NAME") | .id')
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
