apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
  description: Team A
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: admin@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Fluffy&backgroundType=solid,gradientLinear&backgroundColor=ffd5dc,b6e3f4
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: luangazin
spec:
  profile:
    # Intentional no displayName for testing
    email: luan_gazin@yahoo.com.br
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luan&backgroundColor=transparent
  memberOf: [admin]