site_name: Logistics Tracker
site_description: Rastreamento em tempo real de cargas e transporte
plugins:
  - techdocs-core
nav:
  - Visão Geral: index.md
  - Arquitetura: arquitetura.md
  - Operação: operacao.md
