apiVersion: backstage.io/v1alpha1
kind: Environment
metadata:
  name: "ec2_environment"
  environment:
    domain: dummy.vee.codes
    hostedZoneId: Z000000000000000
    vpc_id: vpc-0000000000000
    vpc_name: dummy_demo
    certManagerEmail: dummy@veecode.com
    certManagerIssuerType: staging
  annotations:
    github.com/project-slug: veecode-platform/demo-catalog
    backstage.io/techdocs-ref: dir:.
spec:
  type: env
  lifecycle: development
  owner: "group:default/admin"
