apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.componentId | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    {%- if values.host.includes("github") %}
    github.com/project-slug: ${{ values.repoUrl }}
    {%- endif %}
    {%- if values.host.includes("gitlab") %}
    gitlab.com/project-slug: ${{ values.repoUrl }}
    {%- endif %}
    backstage.io/techdocs-ref: dir:.
    {%- if values.host.includes("github")%}
    github.com/workflows: aws_start_manual.yml,aws_stop_manual.yml,aws_remove_manual.yml
    {%- endif %}
    {%- if values.host.includes("gitlab")%}
    gitlab.com/jobs: Start:START_JOB,Stop:STOP_JOB,Remove:REMOVE_JOB
    {%- endif %}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}