service: ${{ values.componentId }}
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${{ values.stage }}
  region: ${{ values.region }}
  memorySize: 128
  timeout: 10
  {%- if values.bucket == 'custom' %}
  deploymentBucket:
    name: ${file(./config/config.${{ values.stage }}.yaml):deploymentBucket}
    blockPublicAccess: true
    skipPolicySetup: true
  {%- endif %}
  environment:
    INSTANCE_IDS: "{% for instanceId in values.instance_ids | string | list %}${{ instanceId }}{% endfor %}"
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
          - "ec2:StartInstances"
          - "ec2:StopInstances"
          Resource: "*" 
          
plugins:
  - serverless-offline
  
functions:
  start:
    handler: src/handler.start
    name: ${{ values.componentId }}-start
    events:
      - schedule: cron(${{ values.start_time }} ? * ${{ values.schedule_init }}-${{ values.schedule_stop }} *) 
  stop:
    handler: src/handler.stop
    name: ${{ values.componentId }}-stop
    events:
      - schedule: cron(${{ values.stop_time }} ? * ${{ values.schedule_init }}-${{ values.schedule_stop }} *)