apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentName }}
  description: "An example of a static site using NextJs and GHPages"
  annotations:
    github.com/project-slug: ${{ values.repo }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: development
  owner: ${{ values.owner }}
