apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.componentId}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    backstage.io/techdocs-ref: dir:.
    {%- if values.enable_kubernetes_plugin %}
    backstage.io/kubernetes-id: ${{values.componentId | dump}}
    {%- endif %}
    ${{ values.host }}/project-slug: ${{values.repoUrl}}
    {%- if values.enable_vault_plugin %}
    vault.io/secrets-path: ${{values.componentId | dump}}
    {%- endif %}
    {%- if values.enable_grafana_plugin %}
    grafana/dashboard-selector: ${{values.componentId | dump}}
    grafana/alert-label-selector: "alertname=${{values.destination.repo}}"
    {%- endif %}
    {%- if values.enable_argocd_plugin %}
    argocd/proxy-url: '/argocd/api'
    argocd/app-name: ${{values.componentId | dump}}
    {%- endif %}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
