apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: next-demo-template
  title: NextJs Demo Template
  description: Create a static site using NextJs and publish it with GitHub Pages
  annotations:
  backstage.io/techdocs-ref: dir:.
  tags:
    - veeCode-platform-demo
    - nextJs
    - static
    - github
spec:
  owner: veecode-platform/demo
  type: website

  parameters:
    - title: Answer some questions
      description: Define a name for your project.
      required:
        - componentName
      properties:
        componentName:
          title: What is your project name?
          description: Enter your project name
          type: string
          ui:autofocus: true

    - title: Choose a location
      description: |
        This section will ask for details about the Owner and Repository name which will then be used 
        to create a repository in that location using your GitHub credentials.
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Enter an Owner and Repository Name
          description: |
            The Owner should be your GitHub username. The Repository name should be a name that is not one that exists already in your GitHub account.
          type: string
          ui:field: RepoUrlSelector
          reuseName: componentName
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - workflow
            allowedHosts:
              - github.com

  steps:
    - id: list-inputs
      name: List Inputs
      action: debug:log
      input:
        message: |
          The following inputs were provided: 
            - Name: ${{ parameters.componentName }}
          The following inputs were pre-selected:
            - Repo URL: ${{ parameters.repoUrl }}
            - Owner: ${{ (parameters.repoUrl | parseRepoUrl).owner }}
            - Repo: ${{ (parameters.repoUrl | parseRepoUrl).repo }}

    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        token: ${{ secrets.USER_OAUTH_TOKEN or false }}
        values:
          componentName: ${{parameters.componentName}}
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.USER_OAUTH_TOKEN or false }}
        repoVisibility: public
        defaultBranch: main
        description: Repository Created by NextJs Demo Template

  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        title: "GitHub Repository"
      - url: https://github.com/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}/actions/workflows/deploy.yml
        title: "Github Action Workflow"
    text:
      - title: Reminder to Delete Repository
        content: |
          **Note:** You will need to manually delete the resulting repository once you are done.
