name: Deploy Lambda

on:
  push:
    branches: [ ${{ values.default_branch }} ]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      
      - name: Build Project
        run: | 
           npm version
           npm i
           npm install -g serverless

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{'${{'}} secrets.AWS_ACCESS_KEY ${{'}}'}} 
          aws-secret-access-key: ${{'${{'}} secrets.AWS_SECRET_KEY ${{'}}'}}
          aws-region: ${{ values.region }}

      - name: Deploy Project
        run: | 
           sls deploy --stage ${{values.stage}}