apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: devportal-saas-templates
  description: A collection of all VeeCode SaaS Platform templates
spec:
  targets:
    - ./tenant-ec2/template.yaml
