apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.componentId }}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    ${{ values.host }}/project-slug: ${{values.repoUrl}}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{values.componentId | dump}}
    vault.io/secrets-path: ${{values.componentId | dump}}
    grafana/dashboard-selector: ${{values.componentId | dump}}
    grafana/alert-label-selector: "alertname=${{values.componentId}}"
    argocd/proxy-url: '/argocd/api'
    argocd/app-name: ${{values.componentId | dump}}
    kong-manager/service-name: vkpr.${{ values.componentId }}.${{ values.componentId }}-service-0.8080
    kong-manager/instance: /kong-manager/api
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}