apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "ec2-infracost-demo"
  environment:
    cluster_type: ec2
    domain: vee.codes
    ingress_type: kong
    public_ip: 3.217.41.254
  annotations:
    github.com/project-slug: veecode-homolog/hml-ec2-test
    backstage.io/techdocs-ref: dir:..
    # github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml,deploy-dashboard,infracost.yml
    grafana/dashboard-selector: hml-ec2-test
    grafana/alert-label-selector: "alertname=hml-ec2-test"
    infracost/project: ec2-infracost-demo
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$3.217.41.254 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$3.217.41.254:~/.kube/config ~/.kube/config-hml-ec2-test\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"3.217.41.254\")' -i ~/.kube/config-hml-ec2-test\n  export KUBECONFIG=~/.kube/config-hml-ec2-test\n  kubectl get pods -A\n"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
