apiVersion: veecode.backstage.io/v1alpha1
kind: Infracost
metadata:
  name: ec2-infracost-demo
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: FinOps
  lifecycle: experimental
  owner: "group:default/admin"
  estimate:
    $text: ./infracost-base.json
